#!/bin/sh
# The lap design: every sample is 4 laps of equal length timed back to back, lap 0 is warm-up.
# Suites c0, c1, c4, c5 (as in ab.sh) x lap lengths 1, 3, 10, 30, 100 ms x two passes, shuffled.
# Run from lab/ unquiesced (turbo on, unpinned), under the shared lock. Known answer: slow_cpu3/slow_cpu4 = 5/3 exactly; the fast pair
# slow_cpu/slow_cpu2 by the 36-link difference against the canary. Do not edit this file while it runs.
BIN=${BIN:-target/release/lab}
OUT=${OUT:-day/collect/laps-turbo}
export LAB_LAP=4 LAB_FP_HARNESS=1 LAB_SUBSETS=full LAB_PASSES=1 LAB_CAP_S=100000
export LAB_SLOW_ITERS=100 LAB_SLOW2_ITERS=64 LAB_SLOW3_ITERS=3810000 LAB_SLOW4_ITERS=2286000
BASE=slow_cpu,slow_cpu2,f64_sin,parse_u64,btree_miss,warm_dst
comp() {
  case $1 in
    0) echo $BASE ;;
    1) echo $BASE,slow_cpu3,slow_cpu4 ;;
    4) echo $BASE,warm_src ;;
    5) echo $BASE,slow_cpu3,slow_cpu4,fp_heavy,mem_canary,warm_src ;;
  esac
}
dur() {
  case $1 in 1) echo 45s ;; 3) echo 60s ;; 10) echo 120s ;; 30) echo 240s ;; 100) echo 480s ;; esac
}
for pass in 0 1; do
  for c in 0 1 4 5; do for l in 1 3 10 30 100; do echo "$c $l"; done; done | shuf > /tmp/laps-order-$$-$pass
  while read c l; do
    echo "pass $pass comp $c lap ${l}ms start $(date +%T)"
    LAB_LAP_NS=$((l * 1000000)) flock /run/quiet-bench.cpus $BIN collect $(dur $l) $OUT/l$l/c$c/p$pass $(comp $c) 2>&1 | grep -E "rounds in"
  done < /tmp/laps-order-$$-$pass
done
echo "all done $(date +%T)"
